config/routes.rb
Rails.application.routes.draw do
  get 'main/index', :to => 'main#index'
  get 'main/projects', :to => 'main#projects'
  get 'main/publications', :to => 'main#publications'
  get 'main/about_us', :to => 'main#about_us'
  get 'main/find_us', :to => 'main#find_us'
  get 'main/project_details', :to => 'main#project_details'

  resources :projects

  root :to => 'main#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  def project_params
    params.require(:project).permit(:title, :description, :grade, :image_path, :materials, :instructions)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout 'application'

  def index
  end

  def projects
    @projects = Project.all
  end

  def publications
  end

  def about_us
  end

  def find_us
  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def list
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def list
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Making The Maker</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= link_to image_tag("maker_logo_original.png", alt: "Maker logo"), main_index_path, id: "logo", class: "navbar-brand" %>

		<nav id="header-nav">
			<ul id="nav-list">
			  <li class="nav-item">
					<%= link_to "Projects", main_projects_path %>
			  </li>
			  <li class="nav-item">
					<%= link_to "Publications", main_publications_path %>
			  </li>
			  <li class="nav-item">
					<%= link_to "About us", main_about_us_path %>
			  </li>
				<li class="nav-item">
					<%= link_to "Find us", main_find_us_path %>
				</li>
			</ul>
		</nav>
	</header>

	<%= yield %>

	<footer>
		<div class="footer-link-container">
			<div class="footer-link">
				<%= link_to image_tag("tamu_logo.png", alt: "Texas A&M logo"), "http://www.tamu.edu", target: "_blank" %>
			</div>
			<div class="footer-link">
				<%= link_to image_tag("nsf_logo.png", alt: "NSF logo"), "http://www.nsf.gov", target: "_blank" %>
			</div>
		</div>
	</footer>

</body>
</html>

app/views/main/about_us.html.erb
<div id="content-wrapper">
  <h1>About us</h1>

  <div>
    <div class="banner-container">
      <h3>Faculty</h3>
      <h4>Department of Visualization</h4>
      <div class="profile-container col-lg-6">
        <div class="profile-container-img" style="background-image: url('<%= image_path('team/francis_quek.jpg') %>')"></div>
        <p>Dr. Francis Quek <quek@tamu.edu></p>
        </div>

      <div class="profile-container col-lg-6">
        <div class="profile-container-img" style="background-image: url('<%= image_path('team/sharon_lynn_chu.png') %>')"></div>
        <p>Dr. Sharon Lynn Chu <sharilyn@tamu.edu></p>
      </div>

      <h4>Department of Teaching, Learning and Culture</h4>
      <div class="profile-container col-lg-6">
        <div class="profile-container-img" style="background-image: url('<%= image_path('team/lynn_burlbaw.jpg') %>')"></div>
        <p>Dr. Lynn Burlbaw <burlbaw@tamu.edu></p>
      </div>

      <div class="profile-container col-lg-6">
        <div class="profile-container-img" style="background-image: url('<%= image_path('team/patricia_larke.jpeg') %>')"></div>
        <p>Dr. Patricia Larke <plarke@tamu.edu></p>
      </div>

      <h4>Department of Psychology</h4>
      <div class="profile-container col-lg-6">
        <div class="profile-container-img" style="background-image: url('<%= image_path('team/rebecca_schlegel.png') %>')"></div>
        <p>Dr. Rebecca Schlegel <beccaschlegel@tamu.edu></p>
      </div>
    </div>
  </div>

  <div class="banner-container">
    <h3>Former and Current Students</h3>
    <ul class="split-column-2">
      <li> Ana Morales </li>
      <li> Andrew Christy </li>
      <li> Alexander Berman </li>
      <li> Brittany Garcia </li>
      <li> Dherlene Gutierrez </li>
      <li> Genna Angello </li>
      <li> Mario Suarez </li>
      <li> Michael Saenz</li>
      <li> Niloofar Zarei </li>
      <li> Noemie Nakamura </li>
      <li> Rowan Miller </li>
      <li> Stephen Martinez </li>
      <li> Stephen Spencer </li>
      <li> Vanessa Ochoa </li>
    </ul>
  </div>
</div>

app/views/main/find_us.html.erb
<div id="content-wrapper">
  <h1>Find us</h1>

  <h4>In the news</h4>

  <ul>
    <li>
      <a href="http://www.theeagle.com/news/local/educators-look-to-spur-students-interest-in-stem-programs/article_0f9385bf-f461-54b5-8f2a-aec7250452ac.html">
        Educators look to spur students interest in STEM programs
      </a>
    </li>
    <li>
      <a href="https://one.arch.tamu.edu/news/2014/9/30/stem-projects-quek-led/">
        Study eyes influence of STEM activities on children for underrepresented groups
      </a>
    </li>
    <li>
      <a href="http://viz.arch.tamu.edu/about/news/2016/2/18/stem-projects-nsf-funded/">
        Children create STEM-related projects in NSF-funded study
      </a>
    </li>
    <li>
      <a href="http://www.kbtx.com/content/news/Bryan-students-engage-with-Texas-AM-for-hands-on-learning-376648551.html">
        Bryan students engage with Texas A&M for hands-on learning
      </a>
    </li>
  </ul>

  <hr>

  <div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3433.537277472702!2d-96.33983569939505!3d30.618812298075362!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8646839124ea5317%3A0xf34cee4c893330a0!2sLangford+Architecture+Bldg%2C+College+Station%2C+TX+77840!5e0!3m2!1sen!2sus!4v1461007305465"
            width="100%" height="450"
            frameborder="0" style="border:0">
    </iframe>
  </div>

  <div id="contact-links">
    <div class="col-lg-6">
      <%= link_to image_tag("icon_youtube.png"), "https://www.youtube.com/channel/UCxQ3v1a3o3tGN7RSDXN04pg"%>
      <p> Follow us on Youtube </p>
    </div>
    <div class="col-lg-6">
      <%= link_to image_tag("icon_email.png"), "#" %>
      <p> E-mail us at tamu.maker.itest@gmail.com</p>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div id="main-wrapper">
	<!-- Carousel
    ================================================== -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag("slide_01.jpg", class: "slide-img", alt: "First slide") %>
        <div class="container">
          <div class="carousel-caption">
            <h1>Making as the new colored pencils</h1>
            <p>Making the Maker aims to understand how children develop identities and to encourage hands-on learning of STEM projects within the context of the classroom.</p>
          </div>
        </div>
      </div>
      <div class="item">
        <%= image_tag("slide_02.jpg", class: "slide-img", alt: "Second slide") %>
        <div class="container">
          <div class="carousel-caption">
            <h1>A resource hub for educators and researchers</h1>
            <p>Access projects and lesson plans according to specific grades, subjects and materials</p>
          </div>
        </div>
      </div>
      <div class="item">
        <%= image_tag("slide_03.jpg", class: "slide-img", alt: "Third slide") %>
        <div class="container">
          <div class="carousel-caption">
            <h1>Become a part of Making the Maker</h1>
            <p>Learn how to integrate our projects in your school</p>
            <p>
              <a class="general-button" href="#" role="button">Join</a>
            </p>
          </div>
        </div>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- /.carousel -->

  <!-- Three columns of text below the carousel -->
  <div class="container marketing">
    <div class="row">
      <div class="col-lg-4">
        <%= link_to main_projects_path do %>
          <div class="img-circle main-icon" style="background-position: 0px 0px;"></div>
        <% end %>
        <p>Find projects and class plans</p>
      </div>

      <div class="col-lg-4">
        <%= link_to main_find_us_path do %>
          <div class="img-circle main-icon" style="background-position: -140px 0px;"></div>
        <% end %>
        <p>See more about the Making the Maker</p>
      </div>

      <div class="col-lg-4">
        <%= link_to main_publications_path do %>
          <div class="img-circle main-icon" style="background-position: -280px 0px;"></div>
        <% end %>
        <p>Read about our research and findings</p>
      </div>
    </div>
  </div>
</div>

app/views/main/project_details.html.erb
<div id="content-wrapper" class="center-horizontal">
  <%
  params.each do |key,value|
    title = "Project.find_by_id(#{value}).title"
    Rails.logger.warn "Title: #{value}"
    Rails.logger.warn "Title: #{title}"
  end
  %>

  <div class="project-container">
    <div class="project-thumbnail-box">
      <%= image_tag("#{Project.find_by_id(1).image_path}") %>
    </div>

    <div class="project-header-content">
      <div class="project-header-links">
        <%= link_to("Download", "#") %>
        <%= link_to("Print", "#") %>
      </div>
      <h1> Details about <%= "#{Project.find_by_id(1).title}" %> </h1>
      <p> <%= "#{Project.find_by_id(1).description}" %> </p>
    </div>
  </div>

  <div class="project-container">
  </div>

  <div class="project-container">
  </div>
</div>

app/views/main/projects.html.erb
<script type="text/javascript" src="http://vnjs.net/www/project/freewall/example/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="http://vnjs.net/www/project/freewall/freewall.js"></script>

<style type="text/css">
	.free-wall {
		margin: 15px;
	}

	.cell:hover {
		background-color: #f2f2f2;
	}

	.cell img {
		display: block;
		height: 60%;
		width: auto;
		max-width: 60%;
		margin: 15px auto;
	}

	.cell p {
		text-align: center;
	}

</style>

<div id="content-wrapper">
	<h1>Projects</h1>

	<div id="freewall" class="free-wall"></div>

	<script type="text/javascript">
		var w = 200, h = 150, html = ''	;
		<% @projects.each do |project| %>
				var boxOpen = '<div class="cell" style="width:{width}px; height: {height}px; margin-bottom: 15px;" >';

				var boxLink = '<%= link_to image_tag("projects/#{project.image_path}", height: "100%", width: "100%"), project_path(project) %>'
				var boxLabel = '<p> <%= project.title %> </p>'


				var boxClose = '</div>';

				var box = boxOpen + boxLink + boxLabel + boxClose;

			html += box.replace(/\{height\}/g, h).replace(/\{width\}/g, w);
		<% end %>

		$("#freewall").html(html);

		var wall = new Freewall("#freewall");
		wall.reset({
			selector: '.cell',
			animate: true,
			cellW: 200,
			cellH: 150,
			onResize: function() {
				wall.refresh();
			}
		});
		wall.fitWidth();
		// for scroll bar appear;
		$(window).trigger("resize");
	</script>
</div>

app/views/main/publications.html.erb
<div id="content-wrapper">
	<h1>Publications</h1>

	<ul>
		<li class="list-item">
			Chu, S., Angello, G., Saenz, M. and Quek, F. (2017). Fun in Making: Understanding the Experience of Fun and Learning through Curriculum-based Making in the Elementary School Classroom. Journal of Entertainment Computing: Special issue on Maker Technologies to Foster Engagement and Creativity in Learning (Make2Learn), 18, pp. 31-40. http://dx.doi.org/10.1016/j.entcom.2016.08.007
		</li>
		<li class="list-item">
			Chu, S., Quek, F., Bhangaonkar, S., Ging, A. B. and Sridharamurthy, K. (2015). Making the Maker: Nurturing the Maker Mindset. In the International Journal of Child-Computer Interaction: Special Issue on Digital Fabrication in Education, 5, pp 11-19. doi:10.1016/j.ijcci.2015.08.002
		</li>
		<li class="list-item">
			Chu, S. L., Schlegel, R., Quek, F., Christy, A. and Chen K. (2017). I Make, Therefore I Am: An Investigation of Curriculum-based Making on Children's Self-identity. In Proceedings of the CHI Conference on Human Factors in Computing Systems (CHI ’17). Denver, CO. ACM.
		</li>
		<li class="list-item">
			Berman, A., Garcia, B., Nam, B., Chu, S. L. and Quek, F. (2016). Toward a Making Community of Practice: The Social Aspects of Elementary Classroom-Based Making. In Proceedings of FabLearn 2016: 6th Annual Conference on Creativity and Making in Education. Stanford University, Palo Alto.
		</li>
		<li class="list-item">
			Chu, S., Angello, G., Suarez, M. and Quek, F. (2016). A Systemic Analysis of Making in Elementary Schools: Understanding Making for Children through Activity Theory. In Proceedings of International Conference on Advanced Learning Technologies (ICALT ’16). Austin, TX.
		</li>
		<li class="list-item">
			Chu, S., Saenz, M. and Quek, F. (2016). Connectors in Making: Investigating Children’s Motoric Abilities in Making. In Proceedings of International Conference on Interaction Design & Children (IDC ’16). Manchester, UK.
		</li>
		<li class="list-item">
			Angello, G., Chu, S., Quek, F., Osazuwa, O. and Zarei, N. (2016). Making as the New Colored Pencil: Translating Elementary Curricula into Maker Activities. In Proceedings of International Conference on Interaction Design & Children (IDC ’16). Manchester, UK.
		</li>
		<li class="list-item">
			Chu, S. L., Angello, A., Quek, F. and Pyle. S. (2016). Supporting Scientific Model Thinking through Curriculum-based Making. In Proceedings of FabLearn Europe 2016. Preston, UK.
		</li>
		<li class="list-item">
			Chu, S., Quek, F., Saenz, M., Bhangaonkar, S. and Okundaye, O. (2015). Enabling Instrumental Interaction through Electronics Making: Effects on Children’s Storytelling. In Proceedings of International Conference on Interactive Digital Storytelling (ICIDS ’15). Copenhagen, Denmark.
		</li>
	</ul>
</div>

app/views/projects/show.html.erb
<div id="content-wrapper">
  <div class="project-container">
    <div class="project-thumbnail-box">
      <%= image_tag("projects/#{@project.image_path}") %>
    </div>

    <div class="project-header-content">
      <div class="project-header-links">
        <%= link_to("Download", "#") %>
        <%= link_to("Print", "#") %>
      </div>
      <h4> <%= "#{@project.title}" %> </h4>
      <p> <%= "#{@project.description}" %> </p>
    </div>
  </div>

  <hr>

  <!-- Project Materials -->
  <div class="project-container">
    <h4>What you will need</h4>
    <p> <%= "#{@project.materials}" %> </p>
  </div>

  <hr>

  <!-- Project Instructions -->
  <div class="project-container">
    <h4>Step By Step</h4>
    <p> <%= "#{@project.instructions}" %> </p>
  </div>
</div>